AWSTemplateFormatVersion: 2010-09-09
Description: FindResource deployment

Parameters:
  S3Bucket:
    Description: 'The name of the bucket that contains your lambda source code'
    Type: String
    Default: 'elvantech-com'

  S3Folder:
    Description: 'The folder where you loaded the source for the functions.'
    Type: String
    Default: 'Lambda_source'

  S3Key:
    Description: 'Name of the object to load'
    Type: String
    Default: 'FindResource.zip'

Resources:
  # FindResource:
  #   Type: 'Custom::FindResourceFunction'
  #   Properties:
  #     ServiceToken: <lambda arn>
  #     Region: !Ref 'AWS::Region'
  #     SearchType: !Ref SearchType
  #     SearchArgs: !Ref SearchArgs
  FindResourceFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Join
          - '/'
          - - !Ref S3Folder
            - !Ref S3Key
      Handler: 'lambda_handler.handler'
      Role: !GetAtt 
        - LambdaExecutionRole
        - Arn
      Runtime: Python 3.6
      Timeout: '30'
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:Describe*'
                Resource: '*'
